### ISSUE TITLE
[2016 rework] npm install fail with new node

### ISSUE THREAD

**Issue by Bigorneau** [kud/ed-209#62]
Hi, on the rework branch (madx/2016) there is a compile issue with nan module.

```console
% git clone https://github.com/madx/ed-209.git
% cd ed-209
% git checkout origin/2016 -b 2016
% git rev-parse HEAD
bbb2638d138cd3294d5a539eb9e43e52a054b2ed
% node --version
v6.2.2
% npm --version
3.10.2
```

npm install fail.

```console
% npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> iconv@2.1.11 install /tmp/ed-209/node_modules/iconv
> node-gyp rebuild

make: Entering directory '/tmp/ed-209/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
./Release/.deps/Release/obj.target/libiconv/deps/libiconv/lib/iconv.o.d.raw { dev: 39,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 100,
  rdev: 0,
  blksize: 4096,
  ino: 167337305,
  size: 6999,
  blocks: 16,
  atime: 2016-07-18T08:03:25.000Z,
  mtime: 2016-07-18T08:03:25.000Z,
  ctime: 2016-07-18T08:03:25.196Z,
  birthtime: 2016-07-18T08:03:25.196Z }
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:0:
../../nan/nan.h:590:20: error: variable or field AddGCEpilogueCallback declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:590:7: error: GCEpilogueCallback is not a member of v8::Isolate
       v8::Isolate::GCEpilogueCallback callback
       ^~
../../nan/nan.h:591:18: error: expected primary-expression before gc_type_filter
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:596:20: error: variable or field RemoveGCEpilogueCallback declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:596:7: error: GCEpilogueCallback is not a member of v8::Isolate
       v8::Isolate::GCEpilogueCallback callback) {
       ^~
../../nan/nan.h:601:20: error: variable or field AddGCPrologueCallback declared void
       v8::Isolate::GCPrologueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:601:7: error: GCPrologueCallback is not a member of v8::Isolate
       v8::Isolate::GCPrologueCallback callback
       ^~
../../nan/nan.h:602:18: error: expected primary-expression before gc_type_filter
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:607:20: error: variable or field RemoveGCPrologueCallback declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:607:7: error: GCPrologueCallback is not a member of v8::Isolate
       v8::Isolate::GCPrologueCallback callback) {
       ^~
make: *** [iconv.target.mk:103: Release/obj.target/iconv/src/binding.o] Error 1
make: Leaving directory '/tmp/ed-209/node_modules/iconv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.6.2-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/ed-209/node_modules/iconv
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:iconv@2.1.11 iconv@2.1.11 install: `node-gyp rebuild`
npm WARN install:iconv@2.1.11 Exit status 1

> node-icu-charset-detector@0.1.4 install /tmp/ed-209/node_modules/node-icu-charset-detector
> node-gyp rebuild




make: Entering directory '/tmp/ed-209/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
In file included from ../node-icu-charset-detector.cpp:2:0:
../../nan/nan.h:590:20: error: variable or field AddGCEpilogueCallback declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:590:7: error: GCEpilogueCallback is not a member of v8::Isolate
       v8::Isolate::GCEpilogueCallback callback
       ^~
../../nan/nan.h:591:18: error: expected primary-expression before gc_type_filter
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:596:20: error: variable or field RemoveGCEpilogueCallback declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:596:7: error: GCEpilogueCallback is not a member of v8::Isolate
       v8::Isolate::GCEpilogueCallback callback) {
       ^~
../../nan/nan.h:601:20: error: variable or field AddGCPrologueCallback declared void
       v8::Isolate::GCPrologueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:601:7: error: GCPrologueCallback is not a member of v8::Isolate
       v8::Isolate::GCPrologueCallback callback
       ^~
../../nan/nan.h:602:18: error: expected primary-expression before gc_type_filter
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:607:20: error: variable or field RemoveGCPrologueCallback declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:607:7: error: GCPrologueCallback is not a member of v8::Isolate
       v8::Isolate::GCPrologueCallback callback) {
       ^~
make: *** [node-icu-charset-detector.target.mk:86: Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory '/tmp/ed-209/node_modules/node-icu-charset-detector/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.6.2-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/ed-209/node_modules/node-icu-charset-detector
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:node-icu-charset-detector@0.1.4 node-icu-charset-detector@0.1.4 install: `node-gyp rebuild`
npm WARN install:node-icu-charset-detector@0.1.4 Exit status 1
ed-209@0.0.1 /tmp/ed-209
�� babel@6.5.2
�, babel-cli@6.10.1
 �, babel-core@6.10.4
  �, babel-code-frame@6.11.0
   �� esutils@2.0.2
   �� js-tokens@2.0.0
  �, babel-generator@6.11.3
   �, detect-indent@3.0.1
     �� get-stdin@4.0.1
  �� babel-helpers@6.8.0
  �� babel-messages@6.8.0
  �� babel-template@6.9.0
  �, babel-traverse@6.10.4
   �� globals@8.18.0
   �, invariant@2.2.1
     �, loose-envify@1.2.0
       �� js-tokens@1.0.3
  �, babel-types@6.11.1
   �� to-fast-properties@1.0.2
  �� babylon@6.8.4
  �� json5@0.4.0
  �� private@0.1.6
  �� shebang-regex@1.0.0
 �, babel-polyfill@6.9.1
  �� core-js@2.4.1
  �� regenerator-runtime@0.9.5
 �, babel-register@6.9.0
  �, home-or-tmp@1.0.0
   �� os-tmpdir@1.0.1
  �, mkdirp@0.5.1
   �� minimist@0.0.8
  �, source-map-support@0.2.10
    �, source-map@0.1.32
      �� amdefine@1.0.0
 �� babel-runtime@6.9.2
 �, bin-version-check@2.1.0
  �, bin-version@1.0.4
   �, find-versions@1.2.1
     �� array-uniq@1.0.3
     �, meow@3.7.0
      �, camelcase-keys@2.1.0
       �� camelcase@2.1.1
      �� decamelize@1.2.0
      �, loud-rejection@1.6.0
       �, currently-unhandled@0.4.1
        �� array-find-index@1.0.1
       �� signal-exit@3.0.0
      �� map-obj@1.0.1
      �, normalize-package-data@2.3.5
       �� hosted-git-info@2.1.5
       �, is-builtin-module@1.0.0
        �� builtin-modules@1.1.1
       �, validate-npm-package-license@3.0.1
         �, spdx-correct@1.0.2
          �� spdx-license-ids@1.2.1
         �, spdx-expression-parse@1.0.2
           �� spdx-exceptions@1.0.5
      �, read-pkg-up@1.0.1
       �, find-up@1.1.2
        �� path-exists@2.1.0
       �, read-pkg@1.1.0
         �, load-json-file@1.1.0
          �, parse-json@2.2.0
           �, error-ex@1.3.0
             �� is-arrayish@0.2.1
          �� pify@2.3.0
          �, strip-bom@2.0.0
            �� is-utf8@0.2.1
         �� path-type@1.1.0
      �, redent@1.0.0
       �, indent-string@2.1.0
        �� repeating@2.0.1
       �� strip-indent@1.0.1
      �� trim-newlines@1.0.0
     �� semver-regex@1.0.0
  �� minimist@1.2.0
  �� semver@4.3.6
  �, semver-truncate@1.1.0
    �� semver@5.3.0
 �� chalk@1.1.1
 �, chokidar@1.6.0
  �, anymatch@1.3.0
   �� arrify@1.0.1
   �, micromatch@2.3.11
     �, arr-diff@2.0.0
      �� arr-flatten@1.0.1
     �� array-unique@0.2.1
     �, braces@1.8.5
      �, expand-range@1.8.2
       �, fill-range@2.2.3
         �� is-number@2.1.0
         �� isobject@2.1.0
         �� randomatic@1.1.5
         �� repeat-string@1.5.4
      �� preserve@0.2.0
      �� repeat-element@1.1.2
     �, expand-brackets@0.1.5
      �� is-posix-bracket@0.1.1
     �� extglob@0.3.2
     �� filename-regex@2.0.0
     �, kind-of@3.0.3
      �� is-buffer@1.1.3
     �� normalize-path@2.0.1
     �, object.omit@2.0.0
      �, for-own@0.1.4
       �� for-in@0.1.5
      �� is-extendable@0.1.1
     �, parse-glob@3.0.4
      �� glob-base@0.3.0
      �� is-dotfile@1.0.2
     �, regex-cache@0.4.3
       �� is-equal-shallow@0.1.3
       �� is-primitive@2.0.0
  �� async-each@1.0.0
  �� glob-parent@2.0.0
  �� inherits@2.0.1
  �, is-binary-path@1.0.1
   �� binary-extensions@1.5.0
  �, is-glob@2.0.1
   �� is-extglob@1.0.0
  �, readdirp@2.1.0
    �, readable-stream@2.1.4
     �� buffer-shims@1.0.0
     �� core-util-is@1.0.2
     �� isarray@1.0.0
     �� process-nextick-args@1.0.7
     �� string_decoder@0.10.31
     �� util-deprecate@1.0.2
    �� set-immediate-shim@1.0.1
 �, commander@2.9.0
  �� graceful-readlink@1.0.1
 �� convert-source-map@1.2.0
 �� fs-readdir-recursive@0.1.2
 �, glob@5.0.15
  �, inflight@1.0.5
   �� wrappy@1.0.2
  �� once@1.3.3
 �� lodash@4.13.1
 �� log-symbols@1.0.2
 �, output-file-sync@1.1.2
  �� graceful-fs@4.1.4
  �� object-assign@4.1.0
 �� path-exists@1.0.0
 �� path-is-absolute@1.0.0
 �, request@2.73.0
  �� aws-sign2@0.6.0
  �� aws4@1.4.1
  �, bl@1.1.2
   �� readable-stream@2.0.6
  �� caseless@0.11.0
  �, combined-stream@1.0.5
   �� delayed-stream@1.0.0
  �� extend@3.0.0
  �� forever-agent@0.6.1
  �, form-data@1.0.0-rc4
   �� async@1.5.2
  �, har-validator@2.0.6
   �, is-my-json-valid@2.13.1
    �� generate-function@2.0.0
    �, generate-object-property@1.2.0
     �� is-property@1.0.2
    �� jsonpointer@2.0.0
    �� xtend@4.0.1
   �, pinkie-promise@2.0.1
     �� pinkie@2.0.4
  �, hawk@3.1.3
   �� boom@2.10.1
   �� cryptiles@2.0.5
   �� hoek@2.16.3
   �� sntp@1.0.9
  �, http-signature@1.1.1
   �� assert-plus@0.2.0
   �, jsprim@1.3.0
    �� extsprintf@1.0.2
    �� json-schema@0.2.2
    �� verror@1.3.6
   �, sshpk@1.8.3
     �� asn1@0.2.3
     �� assert-plus@1.0.0
     �, dashdash@1.14.0
      �� assert-plus@1.0.0
     �� ecc-jsbn@0.1.1
     �, getpass@0.1.6
      �� assert-plus@1.0.0
     �� jodid25519@1.0.2
     �� jsbn@0.1.0
     �� tweetnacl@0.13.3
  �� is-typedarray@1.0.0
  �� isstream@0.1.2
  �� json-stringify-safe@5.0.1
  �, mime-types@2.1.11
   �� mime-db@1.23.0
  �� node-uuid@1.4.7
  �� oauth-sign@0.8.2
  �� qs@6.2.0
  �� stringstream@0.0.5
  �� tough-cookie@2.2.2
  �� tunnel-agent@0.4.3
 �� slash@1.0.0
 �� source-map@0.5.6
 �, v8flags@2.0.11
   �� user-home@1.1.1
�, babel-preset-es2015@6.9.0
 �� babel-plugin-check-es2015-constants@6.8.0
 �� babel-plugin-transform-es2015-arrow-functions@6.8.0
 �� babel-plugin-transform-es2015-block-scoped-functions@6.8.0
 �� babel-plugin-transform-es2015-block-scoping@6.10.1
 �, babel-plugin-transform-es2015-classes@6.9.0
  �� babel-helper-define-map@6.9.0
  �� babel-helper-function-name@6.8.0
  �� babel-helper-optimise-call-expression@6.8.0
  �� babel-helper-replace-supers@6.8.0
 �� babel-plugin-transform-es2015-computed-properties@6.8.0
 �� babel-plugin-transform-es2015-destructuring@6.9.0
 �� babel-plugin-transform-es2015-duplicate-keys@6.8.0
 �� babel-plugin-transform-es2015-for-of@6.8.0
 �� babel-plugin-transform-es2015-function-name@6.9.0
 �� babel-plugin-transform-es2015-literals@6.8.0
 �, babel-plugin-transform-es2015-modules-commonjs@6.10.3
  �� babel-plugin-transform-strict-mode@6.11.3
 �� babel-plugin-transform-es2015-object-super@6.8.0
 �, babel-plugin-transform-es2015-parameters@6.11.3
  �, babel-helper-call-delegate@6.8.0
   �� babel-helper-hoist-variables@6.8.0
  �� babel-helper-get-function-arity@6.8.0
 �� babel-plugin-transform-es2015-shorthand-properties@6.8.0
 �� babel-plugin-transform-es2015-spread@6.8.0
 �, babel-plugin-transform-es2015-sticky-regex@6.8.0
  �� babel-helper-regex@6.9.0
 �� babel-plugin-transform-es2015-template-literals@6.8.0
 �� babel-plugin-transform-es2015-typeof-symbol@6.8.0
 �, babel-plugin-transform-es2015-unicode-regex@6.11.0
  �, regexpu-core@2.0.0
    �� regenerate@1.3.1
    �� regjsgen@0.2.0
    �, regjsparser@0.1.5
      �� jsesc@0.5.0
 �, babel-plugin-transform-regenerator@6.9.0
   �� babel-plugin-syntax-async-functions@6.8.0
�, chalk@1.1.3
 �� ansi-styles@2.2.1
 �� escape-string-regexp@1.0.5
 �, has-ansi@2.0.0
  �� ansi-regex@2.0.0
 �� strip-ansi@3.0.1
 �� supports-color@2.0.0
�, forever@0.15.1
 �, cliff@0.1.10
  �� colors@1.0.3
  �� eyes@0.1.8
 �� clone@1.0.2
 �� colors@0.6.2
 �, flatiron@0.4.3
  �, broadway@0.3.6
   �� cliff@0.1.9
   �, winston@0.8.0
     �� async@0.2.10
  �� director@1.2.7
  �, optimist@0.6.0
   �� minimist@0.0.10
  �, prompt@0.2.14
    �, read@1.0.7
     �� mute-stream@0.0.6
    �� revalidator@0.1.8
 �, forever-monitor@1.6.0
  �� minimatch@2.0.10
  �, ps-tree@0.0.3
    �, event-stream@0.5.3
      �� optimist@0.2.8
 �, nconf@0.6.9
  �� async@0.2.9
  �� ini@1.3.4
  �, optimist@0.6.0
    �� minimist@0.0.10
 �, nssocket@0.5.3
  �� eventemitter2@0.4.14
  �� lazy@1.0.11
 �� object-assign@3.0.0
 �, optimist@0.6.1
  �� minimist@0.0.10
  �� wordwrap@0.0.3
 �, prettyjson@1.1.3
  �� colors@1.1.2
 �, shush@1.0.0
  �, caller@0.0.1
   �, tape@2.3.3
     �� deep-equal@0.1.2
     �� defined@0.0.0
     �� jsonify@0.0.0
     �� resumer@0.0.0
  �� strip-json-comments@0.1.3
 �� timespan@2.3.0
 �, utile@0.2.1
  �� async@0.2.10
  �� deep-equal@1.0.1
  �� i@0.3.5
  �� ncp@0.4.2
  �, rimraf@2.5.3
    �, glob@7.0.5
      �� fs.realpath@1.0.0
 �, winston@0.8.3
   �� async@0.2.10
   �� cycle@1.0.3
   �� pkginfo@0.3.1
   �� stack-trace@0.0.9
�, irc@0.5.0
 �� irc-colors@1.3.0
�, nodemon@1.9.2  invalid
 �, debug@2.2.0
  �� ms@0.7.1
 �� es6-promise@3.2.1
 �� ignore-by-default@1.0.1
 �, lodash.defaults@3.1.2
  �, lodash.assign@3.2.0
   �, lodash._baseassign@3.2.0
    �� lodash._basecopy@3.0.1
   �, lodash._createassigner@3.1.1
    �� lodash._bindcallback@3.0.1
    �� lodash._isiterateecall@3.0.9
   �, lodash.keys@3.1.2
     �� lodash._getnative@3.9.1
     �� lodash.isarguments@3.0.8
     �� lodash.isarray@3.0.4
  �� lodash.restparam@3.6.1
 �, minimatch@3.0.2
  �, brace-expansion@1.1.5
    �� balanced-match@0.4.1
    �� concat-map@0.0.1
 �, ps-tree@1.1.0
  �, event-stream@3.3.4
    �� duplexer@0.1.1
    �� from@0.1.3
    �� map-stream@0.1.0
    �� pause-stream@0.0.11
    �� split@0.3.3
    �� stream-combiner@0.0.4
    �� through@2.3.8
 �, touch@1.0.0
  �, nopt@1.0.10
    �� abbrev@1.0.9
 �� undefsafe@0.0.3
 �, update-notifier@0.5.0
   �, configstore@1.4.0
    �, osenv@0.1.3
     �� os-homedir@1.0.1
    �� uuid@2.0.2
    �, write-file-atomic@1.1.4
     �� imurmurhash@0.1.4
     �� slide@1.1.6
    �� xdg-basedir@2.0.0
   �� is-npm@1.0.0
   �, latest-version@1.0.1
    �, package-json@1.2.0
      �, got@3.3.1
       �, duplexify@3.4.5
        �� end-of-stream@1.0.0
        �� stream-shift@1.0.0
       �� infinity-agent@2.0.3
       �� is-redirect@1.0.0
       �� is-stream@1.1.0
       �� lowercase-keys@1.0.0
       �� nested-error-stacks@1.0.2
       �� object-assign@3.0.0
       �� prepend-http@1.0.4
       �� read-all-stream@3.1.0
       �� timed-out@2.0.0
      �, registry-url@3.1.0
        �, rc@1.1.6
          �� deep-extend@0.4.1
          �� strip-json-comments@1.0.4
   �, repeating@1.1.3
    �, is-finite@1.0.1
      �� number-is-nan@1.0.0
   �, semver-diff@2.1.0
    �� semver@5.3.0
   �� string-length@1.0.1
�� shellwords@0.1.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN ed-209@0.0.1 No repository field.
npm WARN ed-209@0.0.1 license should be a valid SPDX license expression
npm install  19.00s user 1.38s system 69% cpu 29.452 total
```
Missing few modules the bot fail to start.

```console
% npm start

> ed-209@0.0.1 start /tmp/ed-209
> nodemon index.js

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
/tmp/ed-209/index.js:3
import fs from 'fs'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
[nodemon] app crashed - waiting for file changes before starting...
```

See [node-iconv issue #157](https://github.com/bnoordhuis/node-iconv/issues/157).

I think we could use a Travis module to check any issue with updated node packages breaking something.

Sorry for the encoding, I'm too lazy today to fix it.

**Comment by Bigorneau** [comment]
Until a new release of node-irc the bot doesn't build see [node-irc #463](https://github.com/martynsmith/node-irc/issues/463)
